In [1]:
!pip install nltk

  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)


### 토큰화

In [38]:
# 문장 토큰화 : sent_tokenize
from nltk import sent_tokenize
import nltk
nltk.download('punkt')

text_sample ="You ain't sure yet.\
But I'm for ya. \
All I could want, all I could wish for. \
Nights alone that we miss more. \
And days we save as souvenirs. \
There's no time, I wanna make more time. \
And give you my whole life. \
I left my girl, I’m in Mallorca. \
Hate to leave her, call it torture. \
Remember when I couldn’t hold her. \
Left her baggage for Rimowa."
### " " 만 쓰면 \로 문장이 이어진다는 표시 해줘야함
### """ """ 를 쓸 경우엔 \를 하지 않아도 문장이 이어짐
### (.)콜론을 기준으로 문장을 나눔
sentences = sent_tokenize(text=text_sample)
## 문장을 기준으로 나눠라

print(type(sentences), len(sentences))
print(sentences)

<class 'list'> 10
["You ain't sure yet.But I'm for ya.", 'All I could want, all I could wish for.', 'Nights alone that we miss more.', 'And days we save as souvenirs.', "There's no time, I wanna make more time.", 'And give you my whole life.', 'I left my girl, I’m in Mallorca.', 'Hate to leave her, call it torture.', 'Remember when I couldn’t hold her.', 'Left her baggage for Rimowa.']


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ad\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [39]:
# 단어 토큰화 : word_tokenize
from nltk import word_tokenize

sentence = "You ain't sure yet"

words = word_tokenize(sentence)
## 단어를 기준으로 나눠라

print(type(words), len(words))
print(words)

<class 'list'> 5
['You', 'ai', "n't", 'sure', 'yet']


### 실습 : 텍스트 데이터 전처리

#### 문장 별 단어 토큰화

In [40]:
# 여러 문장들에 대한 단어 토큰화
from nltk import word_tokenize, sent_tokenize

#여러개의 문장으로 된 입력 데이터를 문장별로 단어 토큰화 만드는 함수 생성
def tokenize_text(text):
    
    # 문장별로 분리 토큰
    sentences = sent_tokenize(text)
    
    # 분리된 문장별 단어 토큰화
    word_tokens = [word_tokenize(sentence) for sentence in sentences]
    return word_tokens

# 여러 문장들에 대해 문장별 단어 토큰화 수행.
word_tokens = tokenize_text(text_sample)
print(type(word_tokens),len(word_tokens))
print(word_tokens)

<class 'list'> 10
[['You', 'ai', "n't", 'sure', 'yet.But', 'I', "'m", 'for', 'ya', '.'], ['All', 'I', 'could', 'want', ',', 'all', 'I', 'could', 'wish', 'for', '.'], ['Nights', 'alone', 'that', 'we', 'miss', 'more', '.'], ['And', 'days', 'we', 'save', 'as', 'souvenirs', '.'], ['There', "'s", 'no', 'time', ',', 'I', 'wan', 'na', 'make', 'more', 'time', '.'], ['And', 'give', 'you', 'my', 'whole', 'life', '.'], ['I', 'left', 'my', 'girl', ',', 'I', '’', 'm', 'in', 'Mallorca', '.'], ['Hate', 'to', 'leave', 'her', ',', 'call', 'it', 'torture', '.'], ['Remember', 'when', 'I', 'couldn', '’', 't', 'hold', 'her', '.'], ['Left', 'her', 'baggage', 'for', 'Rimowa', '.']]


#### 영어 스탑워즈 확인해보기

In [41]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ad\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [81]:
# 영어 stopwords 확인
print('영어 stop words 갯수: ', len(nltk.corpus.stopwords.words('english')))

# 영어 stopwords 중 10개만 출력해보자
print(nltk.corpus.stopwords.words('english')[:20])

영어 stop words 갯수:  179
['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his']


In [43]:
# 위 예제 3개 문장에서 얻은 단어 토큰에 대해 stopwords 제거해보자
import nltk

stopwords = nltk.corpus.stopwords.words('english')
all_tokens = []
# 위 예제의 3개의 문장별로 얻은 word_tokens list 에 대해 stop word 제거 Loop
for sentence in word_tokens:
    filtered_words = []
    # 개별 문장별로 tokenize된 sentence list에 대해 stop word 제거 Loop
    for word in sentence:
        # 소문자로 모두 변환합니다.
        word = word.lower()
        # tokenize 된 개별 word가 stop words 들의 단어에 포함되지 않으면 word_tokens에 추가
        if word not in stopwords:
            filtered_words.append(word)
    all_tokens.append(filtered_words)
    
print(all_tokens)

[['ai', "n't", 'sure', 'yet.but', "'m", 'ya', '.'], ['could', 'want', ',', 'could', 'wish', '.'], ['nights', 'alone', 'miss', '.'], ['days', 'save', 'souvenirs', '.'], ["'s", 'time', ',', 'wan', 'na', 'make', 'time', '.'], ['give', 'whole', 'life', '.'], ['left', 'girl', ',', '’', 'mallorca', '.'], ['hate', 'leave', ',', 'call', 'torture', '.'], ['remember', '’', 'hold', '.'], ['left', 'baggage', 'rimowa', '.']]


### Stemmer

In [44]:
from nltk.stem import LancasterStemmer
stemmmer = LancasterStemmer()

print(stemmmer.stem('working'),stemmmer.stem('works'),stemmmer.stem('worked'))
print(stemmmer.stem('amusing'),stemmmer.stem('amuses'),stemmmer.stem('amused'))
print(stemmmer.stem('happier'),stemmmer.stem('happiest'))
print(stemmmer.stem('fancier'),stemmmer.stem('fanciest'))

work work work
amus amus amus
happy happiest
fant fanciest


In [45]:
from nltk.stem import WordNetLemmatizer

import nltk
# nltk.download('wordnet')

lemma = WordNetLemmatizer()

print(lemma.lemmatize('amusing','v'), lemma.lemmatize('amuses','v'), lemma.lemmatize('amused', 'v'))
print(lemma.lemmatize('happier','a'), lemma.lemmatize('happiest','a'))
print(lemma.lemmatize('fancier','a'), lemma.lemmatize('fanciest','v'))

amuse amuse amuse
happy happy
fancy fanciest


Ngram

In [59]:
from nltk import ngrams

sentence = "The Matrix is everywhere its all around us, here even in this room."
words = word_tokenize(sentence)

all_ngrams = ngrams(words, 2)
ngrams = [ngram for ngram in all_ngrams]
print(ngrams)

[('The', 'Matrix'), ('Matrix', 'is'), ('is', 'everywhere'), ('everywhere', 'its'), ('its', 'all'), ('all', 'around'), ('around', 'us'), ('us', ','), (',', 'here'), ('here', 'even'), ('even', 'in'), ('in', 'this'), ('this', 'room'), ('room', '.')]


## 8.3 Bag of Words – BOW

In [60]:
text_sample_01 = 'The Matrix is everywhere its all around us, here even in this room. \
                  You can see it out your window or on your television. \
                  You feel it when you go to work, or go to church or pay your taxes.'
text_sample_02 = 'You take the blue pill and the story ends.  You wake in your bed and you believe whatever you want to believe\
                  You take the red pill and you stay in Wonderland and I show you how deep the rabbit-hole goes.'
text=[]
text.append(text_sample_01); text.append(text_sample_02)
## 한줄에 실행 순서대로 하나씩 시키는 표현 (;)세미콜론
print(text,"\n", len(text))

['The Matrix is everywhere its all around us, here even in this room.                   You can see it out your window or on your television.                   You feel it when you go to work, or go to church or pay your taxes.', 'You take the blue pill and the story ends.  You wake in your bed and you believe whatever you want to believe                  You take the red pill and you stay in Wonderland and I show you how deep the rabbit-hole goes.'] 
 2


CountVectorizer객체 생성 후 fit(), transform()으로 텍스트에 대한 feature vectorization 수행

In [61]:
from sklearn.feature_extraction.text import CountVectorizer

# Count Vectorization으로 feature extraction 변환 수행. 
cnt_vect = CountVectorizer()
cnt_vect.fit(text)

CountVectorizer()

In [62]:
ftr_vect = cnt_vect.transform(text)

피처 벡터화 후 데이터 유형 및 여러 속성 확인

In [63]:
print(type(ftr_vect), ftr_vect.shape)
print(ftr_vect)

<class 'scipy.sparse.csr.csr_matrix'> (2, 51)
  (0, 0)	1
  (0, 2)	1
  (0, 6)	1
  (0, 7)	1
  (0, 10)	1
  (0, 11)	1
  (0, 12)	1
  (0, 13)	2
  (0, 15)	1
  (0, 18)	1
  (0, 19)	1
  (0, 20)	2
  (0, 21)	1
  (0, 22)	1
  (0, 23)	1
  (0, 24)	3
  (0, 25)	1
  (0, 26)	1
  (0, 30)	1
  (0, 31)	1
  (0, 36)	1
  (0, 37)	1
  (0, 38)	1
  (0, 39)	1
  (0, 40)	2
  :	:
  (1, 1)	4
  (1, 3)	1
  (1, 4)	2
  (1, 5)	1
  (1, 8)	1
  (1, 9)	1
  (1, 14)	1
  (1, 16)	1
  (1, 17)	1
  (1, 18)	2
  (1, 27)	2
  (1, 28)	1
  (1, 29)	1
  (1, 32)	1
  (1, 33)	1
  (1, 34)	1
  (1, 35)	2
  (1, 38)	4
  (1, 40)	1
  (1, 42)	1
  (1, 43)	1
  (1, 44)	1
  (1, 47)	1
  (1, 49)	7
  (1, 50)	1


In [64]:
print(cnt_vect.vocabulary_)

{'the': 38, 'matrix': 22, 'is': 19, 'everywhere': 11, 'its': 21, 'all': 0, 'around': 2, 'us': 41, 'here': 15, 'even': 10, 'in': 18, 'this': 39, 'room': 30, 'you': 49, 'can': 6, 'see': 31, 'it': 20, 'out': 25, 'your': 50, 'window': 46, 'or': 24, 'on': 23, 'television': 37, 'feel': 12, 'when': 45, 'go': 13, 'to': 40, 'work': 48, 'church': 7, 'pay': 26, 'taxes': 36, 'take': 35, 'blue': 5, 'pill': 27, 'and': 1, 'story': 34, 'ends': 9, 'wake': 42, 'bed': 3, 'believe': 4, 'whatever': 44, 'want': 43, 'red': 29, 'stay': 33, 'wonderland': 47, 'show': 32, 'how': 17, 'deep': 8, 'rabbit': 28, 'hole': 16, 'goes': 14}


In [65]:
cnt_vect = CountVectorizer(max_features=5, stop_words='english')
cnt_vect.fit(text)
ftr_vect = cnt_vect.transform(text)
print(type(ftr_vect), ftr_vect.shape)
print(cnt_vect.vocabulary_)

<class 'scipy.sparse.csr.csr_matrix'> (2, 5)
{'window': 4, 'pill': 1, 'wake': 2, 'believe': 0, 'want': 3}


ngram_range 확인

In [66]:
cnt_vect = CountVectorizer(ngram_range=(1,2))
cnt_vect.fit(text)
ftr_vect = cnt_vect.transform(text)
print(type(ftr_vect), ftr_vect.shape)
print(cnt_vect.vocabulary_)

<class 'scipy.sparse.csr.csr_matrix'> (2, 125)
{'the': 82, 'matrix': 49, 'is': 42, 'everywhere': 25, 'its': 47, 'all': 0, 'around': 6, 'us': 94, 'here': 32, 'even': 23, 'in': 38, 'this': 88, 'room': 67, 'you': 110, 'can': 15, 'see': 69, 'it': 44, 'out': 57, 'your': 120, 'window': 104, 'or': 53, 'on': 51, 'television': 80, 'feel': 27, 'when': 102, 'go': 29, 'to': 90, 'work': 108, 'church': 17, 'pay': 59, 'taxes': 79, 'the matrix': 84, 'matrix is': 50, 'is everywhere': 43, 'everywhere its': 26, 'its all': 48, 'all around': 1, 'around us': 7, 'us here': 95, 'here even': 33, 'even in': 24, 'in this': 39, 'this room': 89, 'room you': 68, 'you can': 112, 'can see': 16, 'see it': 70, 'it out': 45, 'out your': 58, 'your window': 124, 'window or': 105, 'or on': 55, 'on your': 52, 'your television': 123, 'television you': 81, 'you feel': 113, 'feel it': 28, 'it when': 46, 'when you': 103, 'you go': 114, 'go to': 30, 'to work': 93, 'work or': 109, 'or go': 54, 'to church': 92, 'church or': 18, 'o

### COO

In [50]:
import numpy as np
# BOW 압축(COO)을 위한 라이브러리는 NUMPY

dense = np.array([[3,0,1],[0,2,0]])

In [52]:
from scipy import sparse

# 0이 아닌 데이터 추출
data = np.array([3,1,2])

# 행 위치와 열 위치를 각각 array로 생성
## 3은 (0,0)에 위치 / 1은 (0,2)에 위치 / 2는 (1,1)에 위치
row_pos = np.array([0,0,1])
col_pos = np.array([0,2,1])

# sparse 패키지의 coo_matrix를 이용하여 COO형식으로 희소 행렬 생성
sparse_coo = sparse.coo_matrix((data, (row_pos,col_pos)))

In [58]:
sparse_coo.toarray()
# print(sparse_coo)
# print(sparse_coo.toarray())

array([[3, 0, 1],
       [0, 2, 0]])

### CSR

In [68]:
from scipy import sparse

dense2 = np.array([[0,0,1,0,0,5],
                  [1,4,0,3,2,5],
                  [0,6,0,3,0,0],
                  [2,0,0,0,0,0],
                  [0,0,0,7,0,8],
                  [1,0,0,0,0,0]])

# 0이 아닌 데이터 추출
data2 = np.array([1,5,1,4,3,2,5,6,3,2,7,8,1])

# 행 위치와 열 위치를 각각 array로 생성
row_pos = np.array([0,0,1,1,1,1,1,2,2,3,4,4,5])
col_pos = np.array([2,5,0,1,3,4,5,1,3,0,3,5,0])

# COO 형식으로 변환
sparse_coo = sparse.coo_matrix((data2, (row_pos,col_pos)))

# 행 위치 배열의 고유한 값들의 시작 위치 인덱스를 배열로 생성
row_pos_ind = np.array([0,2,7,9,10,12,13])

# CSR 형식으로 변환
sparse_csr = sparse.csr_matrix((data2, col_pos, row_pos_ind))

print('COO 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인')
print(sparse_coo.toarray())
print('CSR 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인')
print(sparse_csr.toarray())

COO 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인
[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]
CSR 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인
[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]


#### 간단하게 표현

In [75]:
dense3  = np.array([[0,0,1,0,0,5],
                  [1,4,0,3,2,5],
                  [0,6,0,3,0,0],
                  [2,0,0,0,0,0],
                  [0,0,0,7,0,8],
                  [1,0,0,0,0,0]])

coo = sparse.coo_matrix(dense3)
csr = sparse.coo_matrix(dense3)

print(coo.toarray)

<bound method coo_matrix.toarray of <6x6 sparse matrix of type '<class 'numpy.int32'>'
	with 13 stored elements in COOrdinate format>>
