In [1]:
#numpy 의 svd 모듈 import
import numpy as np
from numpy.linalg import svd

#4X4 Random 행렬 a 생성
np.random.seed(121)
a = np.random.randn(6,6)
print(np.round(a,3))

[[-0.212 -0.285 -0.574 -0.44  -0.33   1.184]
 [ 1.615  0.367 -0.014  0.63   1.71  -1.327]
 [ 0.402 -0.191  1.404 -1.969 -0.79  -0.733]
 [ 0.088 -0.5    0.504  0.607  1.166  0.824]
 [-3.087  1.164  1.083  0.486 -1.235 -1.859]
 [ 0.488  0.386 -0.227  0.108  1.72   1.041]]


In [3]:
U, Sigma, Vt = svd(a)
print(U.shape, Sigma.shape, Vt.shape)
print('U matrix:\n', np.round(U, 3))
print('Sigma Value:\n',np.round(Sigma, 3))
print('V transpose matrix: \n',np.round(Vt, 3))

(6, 6) (6,) (6, 6)
U matrix:
 [[ 0.068 -0.396 -0.289  0.004  0.268 -0.827]
 [ 0.307  0.678  0.475  0.149  0.075 -0.44 ]
 [-0.19  -0.406  0.768 -0.446  0.073 -0.068]
 [ 0.216  0.131 -0.202 -0.639 -0.67  -0.195]
 [-0.832  0.416 -0.157 -0.246  0.144 -0.168]
 [ 0.354  0.169 -0.189 -0.557  0.669  0.229]]
Sigma Value:
 [4.719 2.932 2.755 1.58  0.951 0.135]
V transpose matrix: 
 [[ 0.671 -0.172 -0.251  0.064  0.539  0.404]
 [-0.06   0.315  0.043  0.58   0.525 -0.532]
 [ 0.548 -0.016  0.366 -0.474 -0.024 -0.583]
 [ 0.311 -0.027 -0.691  0.254 -0.503 -0.326]
 [-0.088  0.734 -0.406 -0.503  0.182  0.043]
 [ 0.375  0.576  0.398  0.342 -0.383  0.325]]


In [6]:
# Sigma를 다시 0을 포함한 대칭행렬로 변환
Sigma_mat = np.diag(Sigma)
# print(Sigma_mat)
a_ = np.dot(np.dot(U, Sigma_mat), Vt)
print(np.round(a_,3))
## Full SVD

[[-0.212 -0.285 -0.574 -0.44  -0.33   1.184]
 [ 1.615  0.367 -0.014  0.63   1.71  -1.327]
 [ 0.402 -0.191  1.404 -1.969 -0.79  -0.733]
 [ 0.088 -0.5    0.504  0.607  1.166  0.824]
 [-3.087  1.164  1.083  0.486 -1.235 -1.859]
 [ 0.488  0.386 -0.227  0.108  1.72   1.041]]


In [7]:
a[2] = a[0] + a[1]
a[3] = a[0]
print(np.round(a,3))
## multi column linear regression
## multi column linearity 멀티 콜 리니알러티(?)

[[-0.212 -0.285 -0.574 -0.44  -0.33   1.184]
 [ 1.615  0.367 -0.014  0.63   1.71  -1.327]
 [ 1.403  0.082 -0.588  0.189  1.38  -0.143]
 [-0.212 -0.285 -0.574 -0.44  -0.33   1.184]
 [-3.087  1.164  1.083  0.486 -1.235 -1.859]
 [ 0.488  0.386 -0.227  0.108  1.72   1.041]]


In [8]:
#다시 SVD를 수행하여 Sigma 값 확인
U, Sigma, Vt = svd(a)
print(U.shape, Sigma.shape, Vt.shape)
print('Sigma Value:\n', np.round(Sigma,3))

(6, 6) (6,) (6, 6)
Sigma Value:
 [4.926 3.342 1.575 0.529 0.    0.   ]


In [10]:
#U 행렬의 경우는 Sigma와 내적을 수행하므로 Sigma의 앞 2행에 대응되는 앞 2열만 추출
U_ = U[:, :2]
Sigma_ = np.diag(Sigma[:2])
#V 전치 행렬의 경우는 앞 2행만 추출
Vt_ = Vt[:2]
print(U_.shape ,Sigma_.shape, Vt_.shape)
#U, Sigma, Vt의 내적을 수행하며, 다시 원본행렬 복원
a_ = np.dot(np.dot(U_,Sigma_), Vt_)
print(np.round(a_,3))
## Compact SVD

(6, 2) (2, 2) (2, 6)
[[-0.061 -0.424 -0.356 -0.437 -0.462  1.156]
 [ 1.576  0.397  0.075  0.647  1.778 -1.257]
 [ 1.514 -0.026 -0.281  0.21   1.315 -0.101]
 [-0.061 -0.424 -0.356 -0.437 -0.462  1.156]
 [-2.758  0.876  1.227  0.452 -1.598 -2.061]
 [ 1.182 -0.204 -0.378 -0.021  0.85   0.418]]
